/**
 * PIN Code Lookup Utility
 * 
 * Provides City/State auto-detection from 6-digit Indian PIN codes.
 * Uses India Post API for real-time lookup with fallback to common PIN codes.
 */

export interface PinCodeInfo {
  city: string;
  state: string;
  district?: string;
}

// Common PIN codes fallback (for offline/API failure scenarios)
const COMMON_PIN_CODES: Record<string, PinCodeInfo> = {
  '400001': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400002': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400050': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400051': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400053': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400054': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400055': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400056': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400057': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400058': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400059': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400060': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400061': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400062': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400063': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400064': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400065': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400066': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400067': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400068': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400069': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400070': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400071': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400072': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400073': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400074': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400075': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400076': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400077': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400078': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400079': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400080': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400081': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400082': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400083': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400084': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400085': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400086': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400087': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400088': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400089': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400090': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400091': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400092': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400093': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400094': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400095': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400096': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400097': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400098': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400099': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '400100': { city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai' },
  '110001': { city: 'New Delhi', state: 'Delhi', district: 'Central Delhi' },
  '110002': { city: 'New Delhi', state: 'Delhi', district: 'Central Delhi' },
  '110003': { city: 'New Delhi', state: 'Delhi', district: 'Central Delhi' },
  '110004': { city: 'New Delhi', state: 'Delhi', district: 'New Delhi' },
  '110005': { city: 'New Delhi', state: 'Delhi', district: 'New Delhi' },
  '110006': { city: 'New Delhi', state: 'Delhi', district: 'New Delhi' },
  '110007': { city: 'New Delhi', state: 'Delhi', district: 'New Delhi' },
  '110008': { city: 'New Delhi', state: 'Delhi', district: 'New Delhi' },
  '110009': { city: 'New Delhi', state: 'Delhi', district: 'New Delhi' },
  '110010': { city: 'New Delhi', state: 'Delhi', district: 'New Delhi' },
  '560001': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '560002': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '560003': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '560004': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '560005': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '560006': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '560007': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '560008': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '560009': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '560010': { city: 'Bangalore', state: 'Karnataka', district: 'Bangalore Urban' },
  '600001': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '600002': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '600003': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '600004': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '600005': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '600006': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '600007': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '600008': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '600009': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '600010': { city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai' },
  '700001': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '700002': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '700003': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '700004': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '700005': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '700006': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '700007': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '700008': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '700009': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '700010': { city: 'Kolkata', state: 'West Bengal', district: 'Kolkata' },
  '500001': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '500002': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '500003': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '500004': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '500005': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '500006': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '500007': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '500008': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '500009': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '500010': { city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad' },
  '411001': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '411002': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '411003': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '411004': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '411005': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '411006': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '411007': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '411008': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '411009': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '411010': { city: 'Pune', state: 'Maharashtra', district: 'Pune' },
  '380001': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '380002': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '380003': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '380004': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '380005': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '380006': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '380007': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '380008': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '380009': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '380010': { city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad' },
  '302001': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '302002': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '302003': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '302004': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '302005': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '302006': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '302007': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '302008': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '302009': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '302010': { city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur' },
  '226001': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '226002': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '226003': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '226004': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '226005': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '226006': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '226007': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '226008': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '226009': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '226010': { city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow' },
  '160001': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '160002': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '160003': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '160004': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '160005': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '160006': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '160007': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '160008': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '160009': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '160010': { city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh' },
  '452001': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '452002': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '452003': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '452004': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '452005': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '452006': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '452007': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '452008': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '452009': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '452010': { city: 'Indore', state: 'Madhya Pradesh', district: 'Indore' },
  '462001': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '462002': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '462003': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '462004': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '462005': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '462006': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '462007': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '462008': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '462009': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '462010': { city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal' },
  '682001': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '682002': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '682003': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '682004': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '682005': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '682006': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '682007': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '682008': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '682009': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '682010': { city: 'Kochi', state: 'Kerala', district: 'Ernakulam' },
  '695001': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '695002': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '695003': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '695004': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '695005': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '695006': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '695007': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '695008': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '695009': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '695010': { city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram' },
  '751001': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '751002': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '751003': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '751004': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '751005': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '751006': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '751007': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '751008': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '751009': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '751010': { city: 'Bhubaneswar', state: 'Odisha', district: 'Khordha' },
  '800001': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '800002': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '800003': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '800004': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '800005': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '800006': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '800007': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '800008': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '800009': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '800010': { city: 'Patna', state: 'Bihar', district: 'Patna' },
  '834001': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '834002': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '834003': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '834004': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '834005': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '834006': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '834007': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '834008': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '834009': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '834010': { city: 'Ranchi', state: 'Jharkhand', district: 'Ranchi' },
  '781001': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '781002': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '781003': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '781004': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '781005': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '781006': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '781007': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '781008': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '781009': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '781010': { city: 'Guwahati', state: 'Assam', district: 'Kamrup Metropolitan' },
  '440001': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '440002': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '440003': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '440004': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '440005': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '440006': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '440007': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '440008': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '440009': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '440010': { city: 'Nagpur', state: 'Maharashtra', district: 'Nagpur' },
  '395001': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '395002': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '395003': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '395004': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '395005': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '395006': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '395007': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '395008': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '395009': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '395010': { city: 'Surat', state: 'Gujarat', district: 'Surat' },
  '390001': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '390002': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '390003': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '390004': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '390005': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '390006': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '390007': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '390008': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '390009': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '390010': { city: 'Vadodara', state: 'Gujarat', district: 'Vadodara' },
  '360001': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '360002': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '360003': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '360004': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '360005': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '360006': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '360007': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '360008': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '360009': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '360010': { city: 'Rajkot', state: 'Gujarat', district: 'Rajkot' },
  '201001': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201002': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201003': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201004': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201005': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201006': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201007': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201008': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201009': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201010': { city: 'Ghaziabad', state: 'Uttar Pradesh', district: 'Ghaziabad' },
  '201301': { city: 'Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '201302': { city: 'Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '201303': { city: 'Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '201304': { city: 'Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '201305': { city: 'Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '201306': { city: 'Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '201307': { city: 'Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '201308': { city: 'Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '201309': { city: 'Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '201310': { city: 'Greater Noida', state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  '122001': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '122002': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '122003': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '122004': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '122005': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '122006': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '122007': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '122008': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '122009': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '122010': { city: 'Gurgaon', state: 'Haryana', district: 'Gurgaon' },
  '121001': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '121002': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '121003': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '121004': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '121005': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '121006': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '121007': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '121008': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '121009': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '121010': { city: 'Faridabad', state: 'Haryana', district: 'Faridabad' },
  '141001': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '141002': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '141003': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '141004': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '141005': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '141006': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '141007': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '141008': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '141009': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '141010': { city: 'Ludhiana', state: 'Punjab', district: 'Ludhiana' },
  '143001': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '143002': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '143003': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '143004': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '143005': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '143006': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '143007': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '143008': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '143009': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '143010': { city: 'Amritsar', state: 'Punjab', district: 'Amritsar' },
  '180001': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '180002': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '180003': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '180004': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '180005': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '180006': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '180007': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '180008': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '180009': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '180010': { city: 'Jammu', state: 'Jammu and Kashmir', district: 'Jammu' },
  '190001': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '190002': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '190003': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '190004': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '190005': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '190006': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '190007': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '190008': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '190009': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '190010': { city: 'Srinagar', state: 'Jammu and Kashmir', district: 'Srinagar' },
  '248001': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '248002': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '248003': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '248004': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '248005': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '248006': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '248007': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '248008': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '248009': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '248010': { city: 'Dehradun', state: 'Uttarakhand', district: 'Dehradun' },
  '403001': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403002': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403003': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403004': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403005': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403006': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403007': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403008': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403009': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403010': { city: 'Panaji', state: 'Goa', district: 'North Goa' },
  '403601': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '403602': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '403603': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '403604': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '403605': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '403606': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '403607': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '403608': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '403609': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '403610': { city: 'Margao', state: 'Goa', district: 'South Goa' },
  '530001': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '530002': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '530003': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '530004': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '530005': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '530006': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '530007': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '530008': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '530009': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '530010': { city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  '520001': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '520002': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '520003': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '520004': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '520005': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '520006': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '520007': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '520008': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '520009': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '520010': { city: 'Vijayawada', state: 'Andhra Pradesh', district: 'Krishna' },
  '516001': { city: 'Kadapa', state: 'Andhra Pradesh', district: 'Kadapa' },
  '515001': { city: 'Anantapur', state: 'Andhra Pradesh', district: 'Anantapur' },
  '518001': { city: 'Kurnool', state: 'Andhra Pradesh', district: 'Kurnool' },
  '522001': { city: 'Guntur', state: 'Andhra Pradesh', district: 'Guntur' },
  '524001': { city: 'Nellore', state: 'Andhra Pradesh', district: 'Nellore' },
  '517001': { city: 'Tirupati', state: 'Andhra Pradesh', district: 'Tirupati' },
  '570001': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '570002': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '570003': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '570004': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '570005': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '570006': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '570007': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '570008': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '570009': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '570010': { city: 'Mysore', state: 'Karnataka', district: 'Mysore' },
  '580001': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '580002': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '580003': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '580004': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '580005': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '580006': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '580007': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '580008': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '580009': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '580010': { city: 'Hubli', state: 'Karnataka', district: 'Dharwad' },
  '575001': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '575002': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '575003': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '575004': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '575005': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '575006': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '575007': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '575008': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '575009': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '575010': { city: 'Mangalore', state: 'Karnataka', district: 'Dakshina Kannada' },
  '590001': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '590002': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '590003': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '590004': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '590005': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '590006': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '590007': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '590008': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '590009': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '590010': { city: 'Belgaum', state: 'Karnataka', district: 'Belgaum' },
  '641001': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '641002': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '641003': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '641004': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '641005': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '641006': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '641007': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '641008': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '641009': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '641010': { city: 'Coimbatore', state: 'Tamil Nadu', district: 'Coimbatore' },
  '625001': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '625002': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '625003': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '625004': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '625005': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '625006': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '625007': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '625008': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '625009': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '625010': { city: 'Madurai', state: 'Tamil Nadu', district: 'Madurai' },
  '620001': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '620002': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '620003': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '620004': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '620005': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '620006': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '620007': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '620008': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '620009': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '620010': { city: 'Trichy', state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  '636001': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '636002': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '636003': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '636004': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '636005': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '636006': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '636007': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '636008': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '636009': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '636010': { city: 'Salem', state: 'Tamil Nadu', district: 'Salem' },
  '670001': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '670002': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '670003': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '670004': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '670005': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '670006': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '670007': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '670008': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '670009': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '670010': { city: 'Kannur', state: 'Kerala', district: 'Kannur' },
  '673001': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '673002': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '673003': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '673004': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '673005': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '673006': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '673007': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '673008': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '673009': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '673010': { city: 'Kozhikode', state: 'Kerala', district: 'Kozhikode' },
  '676001': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '676002': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '676003': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '676004': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '676005': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '676006': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '676007': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '676008': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '676009': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '676010': { city: 'Malappuram', state: 'Kerala', district: 'Malappuram' },
  '680001': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '680002': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '680003': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '680004': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '680005': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '680006': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '680007': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '680008': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '680009': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '680010': { city: 'Thrissur', state: 'Kerala', district: 'Thrissur' },
  '686001': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '686002': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '686003': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '686004': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '686005': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '686006': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '686007': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '686008': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '686009': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '686010': { city: 'Kottayam', state: 'Kerala', district: 'Kottayam' },
  '688001': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '688002': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '688003': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '688004': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '688005': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '688006': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '688007': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '688008': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '688009': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '688010': { city: 'Alappuzha', state: 'Kerala', district: 'Alappuzha' },
  '691001': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
  '691002': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
  '691003': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
  '691004': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
  '691005': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
  '691006': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
  '691007': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
  '691008': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
  '691009': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
  '691010': { city: 'Kollam', state: 'Kerala', district: 'Kollam' },
};

// Cache for API responses
const pinCodeCache = new Map<string, PinCodeInfo | null>();

/**
 * Validates if a PIN code is in the correct format (6 digits)
 */
export function isValidPinCode(pinCode: string): boolean {
  return /^\d{6}$/.test(pinCode);
}

/**
 * Lookup PIN code information from API with fallback to static data
 */
export async function lookupPinCode(pinCode: string): Promise<PinCodeInfo | null> {
  // Validate format
  if (!isValidPinCode(pinCode)) {
    return null;
  }

  // Check cache first
  if (pinCodeCache.has(pinCode)) {
    return pinCodeCache.get(pinCode) || null;
  }

  // Check static fallback first (faster)
  if (COMMON_PIN_CODES[pinCode]) {
    const result = COMMON_PIN_CODES[pinCode];
    pinCodeCache.set(pinCode, result);
    return result;
  }

  // Try India Post API
  try {
    const response = await fetch(`https://api.postalpincode.in/pincode/${pinCode}`, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error('API request failed');
    }

    const data = await response.json();
    
    if (data && data[0] && data[0].Status === 'Success' && data[0].PostOffice && data[0].PostOffice.length > 0) {
      const postOffice = data[0].PostOffice[0];
      const result: PinCodeInfo = {
        city: postOffice.District || postOffice.Name,
        state: postOffice.State,
        district: postOffice.District,
      };
      pinCodeCache.set(pinCode, result);
      return result;
    }

    // API returned but no match
    pinCodeCache.set(pinCode, null);
    return null;
  } catch (error) {
    // API failed, return null (we already checked static data)
    console.warn('PIN code lookup API failed:', error);
    pinCodeCache.set(pinCode, null);
    return null;
  }
}

/**
 * Synchronous lookup from static data only (for immediate display)
 */
export function lookupPinCodeSync(pinCode: string): PinCodeInfo | null {
  if (!isValidPinCode(pinCode)) {
    return null;
  }
  
  return COMMON_PIN_CODES[pinCode] || null;
}

/**
 * Format PIN code info for display
 */
export function formatPinCodeInfo(info: PinCodeInfo): string {
  return `${info.city}, ${info.state}`;
}
