// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdcoukzjumcfwskkcxkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkY291a3pqdW1jZndza2tjeGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODU5MDUsImV4cCI6MjA3MDY2MTkwNX0.sXDF266qi1q24gKRRxX0kv7U-rkPR1LZc0G524OIFlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});